function openLightbox(src){const l=document.getElementById('lightbox');document.getElementById('lightbox-img').src=src;l.classList.add('active')}function closeLightbox(){document.getElementById('lightbox').classList.remove('active')}function submitForm(e){e.preventDefault();const f=new FormData(e.target),telephone=(f.get('telephone')||'').trim(),email=(f.get('email')||'').trim();if(!telephone&&!email){alert('Merci d’indiquer un numéro de téléphone ou une adresse e-mail.');return}const contact=f.get('contact')||'Peu importe',subject='Nouvelle demande de contact - '+f.get('nom'),body=`Bonjour Prise 2 Froid,

Je souhaite être contacté concernant mon projet.

Nom : ${f.get('nom')}
Téléphone : ${telephone||'Non renseigné'}
E-mail : ${email||'Non renseignée'}
Commune : ${f.get('commune')}
Projet : ${f.get('projet')}
Préférence de contact : ${contact}
Message : ${f.get('message')||'Aucun message'}`;window.location.href='mailto:prise2froid@gmail.com?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body)}document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLightbox()});
let carouselIndex=0;function carouselVisible(){return window.innerWidth<=600?1:window.innerWidth<=900?2:3}function renderCarousel(){const track=document.getElementById('carouselTrack'),dots=document.getElementById('carouselDots');if(!track||!dots)return;const slides=[...track.children],visible=carouselVisible(),max=Math.max(0,slides.length-visible);carouselIndex=Math.min(carouselIndex,max);const step=slides[0].getBoundingClientRect().width+15;track.style.transform='translateX('+(-carouselIndex*step)+'px)';dots.innerHTML='';for(let i=0;i<=max;i++){const d=document.createElement('button');d.type='button';d.className='carousel-dot'+(i===carouselIndex?' active':'');d.setAttribute('aria-label','Afficher la position '+(i+1));d.onclick=()=>goCarousel(i);dots.appendChild(d)}const prev=document.querySelector('.carousel-prev'),next=document.querySelector('.carousel-next');if(prev)prev.disabled=carouselIndex===0;if(next)next.disabled=carouselIndex===max}function moveCarousel(direction){carouselIndex+=direction;renderCarousel()}function goCarousel(index){carouselIndex=index;renderCarousel()}window.addEventListener('resize',renderCarousel);document.addEventListener('DOMContentLoaded',()=>{const viewport=document.getElementById('carouselViewport');let startX=0;if(viewport){viewport.addEventListener('touchstart',e=>startX=e.touches[0].clientX,{passive:true});viewport.addEventListener('touchend',e=>{const delta=e.changedTouches[0].clientX-startX;if(Math.abs(delta)>45)moveCarousel(delta<0?1:-1)},{passive:true})}renderCarousel()});
function openPacStory(event){event.preventDefault();const section=document.getElementById('pac-air-air');if(!section)return;section.classList.add('is-open');event.currentTarget.setAttribute('aria-expanded','true');requestAnimationFrame(()=>section.scrollIntoView({behavior:'smooth',block:'start'}))}document.addEventListener('DOMContentLoaded',()=>{const trigger=document.querySelector('.pac-card');if(trigger)trigger.addEventListener('click',openPacStory)});
